version: '3.4'

services:
  app:
    build: .
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/stationary_store
    ports:
      - 8000:8000
    networks:
      - main
    restart: always


networks:
  main:

